### ISSUE TITLE
Email is not registering

### ISSUE THREAD

**Issue by nikhilbhatt** [kuldeep3/e-library#3]
The application is not registering my email. the error is 'Please enter valid email'.
this is the early bug that I found in the app.

**Comment by kuldeep3** [comment]
Thanks for the information @nikhilbhatt. I will try to fix this issue as soon as possible.

**Comment by kuldeep3** [comment]
@nikhilbhatt The issue has been fixed. Please have a look at it.


![sc1](https://user-images.githubusercontent.com/37093310/74591926-6b828180-5042-11ea-97aa-2d7ab2586764.jpg)
